// Package report Code generated by swaggo/swag. DO NOT EDIT
package report

import "github.com/swaggo/swag"

const docTemplatereport = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/report/daily-fiat": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "按日期行、法币列返回完成单量、USDT 完成额、对冲指标，以及已收/待收/应收利润。side 仅筛选不分组。金额字段为字符串。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "报表"
                ],
                "summary": "法币每日完成/对冲/利润报表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期（含），2006-01-02 或 2006-01-02 15:04:05，不传默认最近 30 天",
                        "name": "beginTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期（含），格式同上，不传默认今天",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "法币过滤，逗号分隔，如 AED,AUD,BRL,CAD",
                        "name": "fiatCurrency",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "方向筛选，1/BUY 或 2/SELL，不传则买卖合计",
                        "name": "side",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DailyFiatGetReply"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/dto.DailyFiatGetReply"
                        }
                    },
                    "500": {
                        "description": "查询失败 / 业务库未初始化",
                        "schema": {
                            "$ref": "#/definitions/dto.DailyFiatGetReply"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.DailyFiatGetReply": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/dto.DailyFiatGetResp"
                },
                "msg": {
                    "type": "string",
                    "example": "查询成功"
                },
                "requestId": {
                    "type": "string"
                }
            }
        },
        "dto.DailyFiatGetResp": {
            "type": "object",
            "properties": {
                "beginTime": {
                    "type": "string",
                    "example": "2026-07-30"
                },
                "currencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endTime": {
                    "type": "string",
                    "example": "2026-08-17"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DailyFiatRow"
                    }
                }
            }
        },
        "dto.DailyFiatRow": {
            "type": "object",
            "properties": {
                "actualProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "completedOrderCount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "estimatedProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "groupDate": {
                    "type": "string",
                    "example": "2026-08-01"
                },
                "hedgedOrderCount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "hedgedVolumeUsdt": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "receivableProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "totalActualProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "totalEstimatedProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "totalProfit": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "volumeCompleted": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInforeport holds exported Swagger Info so clients can modify it
var SwaggerInforeport = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "数据分析报表 API",
	Description:      "数据分析服务报表接口，供前端对接。金额类字段为字符串。",
	InfoInstanceName: "report",
	SwaggerTemplate:  docTemplatereport,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforeport.InstanceName(), SwaggerInforeport)
}
